modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="classic_adventure"
version="${mod_version}"
displayName="Classic Adventure"
authors="User"
description="Replicates pre-1.7.10 adventure mode mining restrictions."

[[dependencies.classic_adventure]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.classic_adventure]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"